### ISSUE TITLE
Improve CSS of the page

### ISSUE THREAD

**Issue by jecisc** [pharo-project/pharo-gsoc#54]
It would be great to add this in the CSS of the topics page:
```css
td {
    white-space: pre-line;
}
```

It would keep line returns in the tables and not put everything in one line.
